apiVersion: v1
kind: Service
metadata:
  name: churn-api-service
  namespace: churn-ml
spec:
  selector:
    app: churn-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
